Repository Dezenix/frontend-html-css-js, pull requests merged in 2021-12, with the labels that each got.

#19 Added Analog Clock (SWoC)
  Analog_Clock/index.html
  Analog_Clock/script.js
  Analog_Clock/style.css
Labels: Swoc Lv2, SWoC

#38 Fix: Added code for 'Pre Loader Animation' (Issue #37).
  Loader/Loader_03/README.md
  Loader/Loader_03/assets/Loader_3.gif
  Loader/Loader_03/code/index.html
  Loader/Loader_03/code/style.css
Labels: Swoc Lv1, SWoC

#45 feat: added circular navigation bar
  Circular navbar/README.md
  Circular navbar/index.html
  Circular navbar/preview.gif
  Circular navbar/style.css
Labels: Swoc Lv2, SWoC

#44 added neumorphism toggle buttons
  Buttons/Toggle buttons_01/README.md
  Buttons/Toggle buttons_01/assets/preview.gif
  Buttons/Toggle buttons_01/code/index.html
  Buttons/Toggle buttons_01/code/style.css
Labels: Swoc Lv2, SWoC

#46 Fix: Added code for 'Broken Mirror Text Animation' (Issue #40).
  Text_Animations/Text_Animation_01/README.md
  Text_Animations/Text_Animation_01/assets/Text_Animation.gif
  Text_Animations/Text_Animation_01/code/index.html
  Text_Animations/Text_Animation_01/code/style.css
Labels: Swoc Lv2, SWoC

#47 Code added for Issue #32 10DoC by Dipak Ghosh
  Pop Up Modals/Movie Ticket Grid/index.css
  Pop Up Modals/Movie Ticket Grid/index.html
Labels: 10DoC

#53 feat: added 3D Carousel
  Carousels/3D Carousel_01/README.md
  Carousels/3D Carousel_01/code/index.html
  Carousels/3D Carousel_01/code/style.css
Labels: Swoc Lv3, SWoC

#55 Code for the issue Dezenix#33 10DoC by Arpan Sharma after Changes
  UI HOVER EFFECT/README.md
  UI HOVER EFFECT/assets/Hover  UI Preview.gif
  UI HOVER EFFECT/assets/parrot-3695678__340.jpg
  UI HOVER EFFECT/code/css/style.css
  UI HOVER EFFECT/code/index.html
  UI HOVER EFFECT/code/js/tilt.js
Labels: 10DoC

#52 Fix : Responsive Accordion #49
  Accordion/Responsive_Accordion_01/README.md
  Accordion/Responsive_Accordion_01/assets/Accodion_Preview.png
  Accordion/Responsive_Accordion_01/code/index.html
  Accordion/Responsive_Accordion_01/code/style.css
Labels: Swoc Lv2, SWoC

#42 Completed Timeine onScroll Animation
  Timelines/Timeline_onScroll_Animation_1/Priview_timeline.png
  Timelines/Timeline_onScroll_Animation_1/README.md
  Timelines/Timeline_onScroll_Animation_1/app.js
  Timelines/Timeline_onScroll_Animation_1/images/logoImage_1.png
  Timelines/Timeline_onScroll_Animation_1/images/logoImage_2.png
  Timelines/Timeline_onScroll_Animation_1/images/logoImage_3.png
  Timelines/Timeline_onScroll_Animation_1/images/logoImage_4.png
  Timelines/Timeline_onScroll_Animation_1/index.html
  Timelines/Timeline_onScroll_Animation_1/style.css
Labels: Swoc Lv2, SWoC

#34 Side Hamburger Navbar
  Navbars/Side_Navbar_02/README.md
  Navbars/Side_Navbar_02/code/index.html
  Navbars/Side_Navbar_02/code/script.js
  Navbars/Side_Navbar_02/code/style.css
Labels: Swoc Lv1, SWoC

#63 Code added for issue #59 by Dipak Ghosh
  Product_Display_Cards/Product_Card_03/assets/css/index.css
  Product_Display_Cards/Product_Card_03/assets/img/buy.png
  Product_Display_Cards/Product_Card_03/assets/img/colors.png
  Product_Display_Cards/Product_Card_03/assets/img/info.png
  Product_Display_Cards/Product_Card_03/assets/img/prod.png
  Product_Display_Cards/Product_Card_03/assets/img/sizes.png
  Product_Display_Cards/Product_Card_03/index.html
  Product_Display_Cards/Product_Card_03/preview.md
Labels: 10DoC

#64 Animated login
  Login_Forms/Animated_submit/README.md
  Login_Forms/Animated_submit/code/index.html
  Login_Forms/Animated_submit/code/style.css
Labels: 10DoC

#65 Neon 404 Error Dezenix#58 10DoC by Arpan Sharma
  Error 404/README.md
  Error 404/assets/preview.gif
  Error 404/index.html
  Error 404/style.css
Labels: 10DoC

#62 Simple Login Form
  Login_Forms/Simple Login Form/README.md
  Login_Forms/Simple Login Form/code/index.html
  Login_Forms/Simple Login Form/code/style.css
Labels: Swoc Lv1, SWoC
