Repository Dezenix/frontend-html-css-js, pull requests merged in 2022-02, with the labels that each got.

#114 Buttons Hover Effects
  Buttons/Button Hover Effects/README.md
  Buttons/Button Hover Effects/code/index.html
  Buttons/Button Hover Effects/code/style.css
Labels: Swoc Lv3, SWoC

#113 Fullscreen Overlay Navigation with Hover Effect
  Navbars/Fullscreen_Overlay_Navigation_01/README.md
  Navbars/Fullscreen_Overlay_Navigation_01/assets/1.jpg
  Navbars/Fullscreen_Overlay_Navigation_01/assets/2.jpg
  Navbars/Fullscreen_Overlay_Navigation_01/code/index.html
  Navbars/Fullscreen_Overlay_Navigation_01/code/style.css
Labels: Swoc Lv1, SWoC

#108 Text animations
  Text_Animations/Text_Animation_02/README.md
  Text_Animations/Text_Animation_02/code/index.html
  Text_Animations/Text_Animation_02/code/style.css
  Text_Animations/Text_Animation_03/README.md
  Text_Animations/Text_Animation_03/code/index.html
  Text_Animations/Text_Animation_03/code/style.css
  Text_Animations/Text_Animation_04/README.md
  Text_Animations/Text_Animation_04/code/index.html
  Text_Animations/Text_Animation_04/code/style.css
  Text_Animations/Text_Animation_05/README.md
  Text_Animations/Text_Animation_05/code/index.html
  Text_Animations/Text_Animation_05/code/style.css
Labels: Swoc Lv2, SWoC

#105 Snake Game
  Games/Snake_Game/README.md
  Games/Snake_Game/images/apple1.png
  Games/Snake_Game/images/mango.png
  Games/Snake_Game/images/pear.png
  Games/Snake_Game/images/wp2409705.jpg
  Games/Snake_Game/index.html
  Games/Snake_Game/preview.png
  Games/Snake_Game/script.js
  Games/Snake_Game/style.css
Labels: Swoc Lv3, SWoC

#117 Social Media Buttons
  Buttons/Social Media Buttons/Social_Media_Buttons_01/README.md
  Buttons/Social Media Buttons/Social_Media_Buttons_01/code/index.html
  Buttons/Social Media Buttons/Social_Media_Buttons_01/code/style.css
  Buttons/Social Media Buttons/Social_Media_Buttons_02/README.md
  Buttons/Social Media Buttons/Social_Media_Buttons_02/code/index.html
  Buttons/Social Media Buttons/Social_Media_Buttons_02/code/style.css
  Buttons/Social Media Buttons/Social_Media_Buttons_03/README.md
  Buttons/Social Media Buttons/Social_Media_Buttons_03/code/index.html
  Buttons/Social Media Buttons/Social_Media_Buttons_03/code/style.css
  Buttons/Social Media Buttons/Social_Media_Buttons_04/README.md
  Buttons/Social Media Buttons/Social_Media_Buttons_04/code/index.html
  Buttons/Social Media Buttons/Social_Media_Buttons_04/code/style.css
  Buttons/Social Media Buttons/Social_Media_Buttons_05/README.md
  Buttons/Social Media Buttons/Social_Media_Buttons_05/code/index.html
  Buttons/Social Media Buttons/Social_Media_Buttons_05/code/style.css
Labels: Swoc Lv3, SWoC
