Repository Dezenix/frontend-html-css-js, pull requests merged in 2022-04, with the labels that each got.

#151 Adding the otp page
  Otp Page/Assets/OTP Page - Google Chrome 07-04-2022 16_25_37.png
  Otp Page/Assets/OTP Page - Google Chrome 2022-04-07 16-13-09.mp4
  Otp Page/README.md
  Otp Page/index.html
  Otp Page/index.js
  Otp Page/styles.css
Labels: GSSoC22, Level2

#149 3D carousel 2 added
  Carousels/3D Carousel_02/README.md
  Carousels/3D Carousel_02/images/818JxxUzo4L.jpg
  Carousels/3D Carousel_02/images/basketball-LeBron-James-Cleveland-Cavaliers-2018.jpg
  Carousels/3D Carousel_02/images/dcovnovcover_traehzlogo.jpg
  Carousels/3D Carousel_02/images/doncic_luka1280-1-1040x572.jpg
  Carousels/3D Carousel_02/images/download.jpg
  Carousels/3D Carousel_02/images/ezgif.com-gif-maker.gif
  Carousels/3D Carousel_02/images/images.jpg
  Carousels/3D Carousel_02/index.html
  Carousels/3D Carousel_02/index.js
  Carousels/3D Carousel_02/styles.css
Labels: GSSoC22, Level2

#153 Notes app added
  Notes_app/index.html
  Notes_app/script.js
  Notes_app/style.css
Labels: GSSoC22, Level3

#157 Added Anime profile pic genrator to the current repository
  Anime App/README.md
  Anime App/anime.png.png
  Anime App/index.html
  Anime App/script.js
  Anime App/style.css
Labels: GSSoC22, Level2

#158 Added Responsive Profile Card
  Cards/Personal Profile Card/Readme.md
  Cards/Personal Profile Card/code/index.html
  Cards/Personal Profile Card/code/script.js
  Cards/Personal Profile Card/code/style.css
Labels: GSSoC22, Level1

#164 Dictionary app added
  Dictionary_App/index.html
  Dictionary_App/script.js
  Dictionary_App/styles.css
Labels: GSSoC22, Level2

#160 Added responsive Landing page
  Responsive Landing page/README.md
  Responsive Landing page/index.html
  Responsive Landing page/logo.png
  Responsive Landing page/person.png
  Responsive Landing page/responsiveWeb.png.png
  Responsive Landing page/script.js
  Responsive Landing page/shape.png
  Responsive Landing page/style.css
Labels: GSSoC22, Level3
