Repository Dezenix/frontend-html-css-js, pull requests merged in 2022-05, with the labels that each got.

#170 Added Dice roller
  Dice Roller/app/a/1.svg
  Dice Roller/app/a/2.svg
  Dice Roller/app/a/3.svg
  Dice Roller/app/a/4.svg
  Dice Roller/app/a/5.svg
  Dice Roller/app/a/6.svg
  Dice Roller/app/a/roll.mp3
  Dice Roller/app/index.html
  Dice Roller/app/script.js
  Dice Roller/app/style.css
  Dice Roller/ico/icon.png
  Dice Roller/readme
Labels: GSSoC22, Level1

#139 changes made
  Log-In&Sign-Up/assets/img1.jpg
  Log-In&Sign-Up/index.html
  Log-In&Sign-Up/style.css
Labels: GSSoC22, Level1

#125 Update style.css
  Cards/Weather Widget Card/code/style.css
Labels: GSSoC22, Level1

#175 responsive contact form
  ContactForm/contact.html
  ContactForm/style.css
Labels: GSSoC22, Level2

#174 Added Coin tosser
  Coin Tosser/Authenticity.html
  Coin Tosser/allJavaScript.js
  Coin Tosser/coinFaces.html
  Coin Tosser/coinStyling.css
  Coin Tosser/index.html
  Coin Tosser/manifest.json
  Coin Tosser/pictures/back.png
  Coin Tosser/pictures/heads.png
  Coin Tosser/pictures/pound-heads.png
  Coin Tosser/pictures/pound-tails.png
  Coin Tosser/pictures/pound.png
  Coin Tosser/pictures/settings.svg
  Coin Tosser/pictures/tails.png
  Coin Tosser/pictures/twoface-heads.png
  Coin Tosser/pictures/twoface-tails.png
  Coin Tosser/pictures/twoface.png
  Coin Tosser/readme.md
  Coin Tosser/settings.html
  Coin Tosser/tab-icon-not.png
  Coin Tosser/tab-icon.png
Labels: GSSoC22, Level2

#178 Added Feedback UI to the current Repository.
  Feedback-Popups/Feedback-UI/README.md
  Feedback-Popups/Feedback-UI/feedback.png
  Feedback-Popups/Feedback-UI/index.html
  Feedback-Popups/Feedback-UI/script.js
  Feedback-Popups/Feedback-UI/style.css
Labels: GSSoC22, Level2

#189 Added O'reilly Website UI
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/amazon-appstore-logo.png
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/app-store-logo.png
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/cert-vendor-logos.png
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/css1.css
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/css2.css
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/device-image1-800x600-20210224.jpg
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/device-image2-800x600-20220218.jpg
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/device-image3-800x600-20210224.jpg
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/device-image4-800x600-20210224.jpg
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/diversity_jobs_2021.png
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/google-play-logo.png
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/home_plot3_lot_600x600.jpg
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/homepage_cloud_blurb_1067x620.jpg
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/oreilly_logo_mark_red.svg
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/roku-tv-logo.png
  O'Reilly UI/O'Reilly Media - Technology and Business Training_files/the_cost_of_doing_nothing_screenshot.png
  O'Reilly UI/index.html
  O'Reilly UI/readme.md
Labels: GSSoC22, Level3

#186 Food panda Website Clone
  Food Panda Website Clone/foodpanda _ food and more, delivered.html
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/Bangladesh.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/HK-1.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/HU.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/MY.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/PH.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/PK.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/SG-1.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/SK.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/TH.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/TW.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/cambodia-e1582274460360.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/css1.css
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/css2.css
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/food-panda-logo-vector.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/foodpanda-rider-opt.jpg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/foodpanda-tuna-opt-scaled.jpg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/ic_social_facebook.svg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/ic_social_linkedin.svg
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/laos-e1582274407429.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/myanmar-e1582274330314.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/romania.png
  Food Panda Website Clone/foodpanda _ food and more, delivered_files/team_bg-opt.jpg
  Food Panda Website Clone/readme.md
Labels: GSSoC22, Level3

#182 Added animated 3d box project.
  3d boxes/index.html
  3d boxes/script.js
  3d boxes/style.css
Labels: GSSoC22, Level3

#180 Added responsive faq accordin menu
  Accordion/Accordion_Menu_03/Readme.md
  Accordion/Accordion_Menu_03/assets/FAQ.PNG
  Accordion/Accordion_Menu_03/code/index.html
  Accordion/Accordion_Menu_03/code/script.js
  Accordion/Accordion_Menu_03/code/style.css
Labels: GSSoC22, Level3

#191 Drag And Drop Uploads
  DRag and Drop Uploads/README.md
  DRag and Drop Uploads/icons8-open-file-folder-48.png
  DRag and Drop Uploads/index.html
  DRag and Drop Uploads/script.js
  DRag and Drop Uploads/style.css
Labels: GSSoC22, Level3

#198 Blur DOM Loader
  Blur Image Loader/1626442057935.jpg
  Blur Image Loader/README.md
  Blur Image Loader/index.html
  Blur Image Loader/script.js
  Blur Image Loader/style.css
Labels: GSSoC22, Level2

#197 3D Login Form
  3D login form DENZIX/README.md
  3D login form DENZIX/index.html
  3D login form DENZIX/style.css
Labels: GSSoC22, Level2

#229 Random Password Generator
  random Password generator/README.md
  random Password generator/index.html
  random Password generator/script.js
  random Password generator/style.css
Labels: GSSoC22, Level2

#228 Real Estate Project Blueprint
  Real Estate Project Blueprint/2.jpg
  Real Estate Project Blueprint/4.jpg
  Real Estate Project Blueprint/Floor plan.jpg
  Real Estate Project Blueprint/ISOMETRIC VIEW.jpeg
  Real Estate Project Blueprint/README.md
  Real Estate Project Blueprint/index.html
  Real Estate Project Blueprint/isometric view.html
  Real Estate Project Blueprint/reference.jpeg
  Real Estate Project Blueprint/script.js
  Real Estate Project Blueprint/singleBuild.html
  Real Estate Project Blueprint/style.css
Labels: GSSoC22, Level2

#227 Liquify Capsule
  Liquify capsule/README.md
  Liquify capsule/index.html
  Liquify capsule/style.css
Labels: GSSoC22, Level2

#193 Added animated form.
  Forms/animate-form/README.md
  Forms/animate-form/index.html
  Forms/animate-form/script.js
  Forms/animate-form/style.css
Labels: GSSoC22, Level2

#201 Gangsta Glowers
  Gangsta Glowers/README.md
  Gangsta Glowers/index.html
  Gangsta Glowers/style.css
Labels: GSSoC22, Level2

#203 Added responsive footer UI
  Footers/Footer_03/Code/index.html
  Footers/Footer_03/Code/script.js
  Footers/Footer_03/Code/style.css
  Footers/Footer_03/Readme.md
Labels: GSSoC22, Level2

#205 Added Movie Search App
  Movie-Search-App/Movie-Search-App.png
  Movie-Search-App/README.md
  Movie-Search-App/index.html
  Movie-Search-App/script.js
  Movie-Search-App/style.css
Labels: GSSoC22, Level3

#206 Added Snake Game
  Snake-Game/README.md
  Snake-Game/Snake-Game.png
  Snake-Game/images/apple1.png
  Snake-Game/images/mango.png
  Snake-Game/images/pear.png
  Snake-Game/images/wp2409705.jpg
  Snake-Game/index.html
  Snake-Game/script.js
  Snake-Game/style.css
Labels: GSSoC22, Level3

#208 GitHub fetch Added.
  Github_fetch/README.md
  Github_fetch/index.html
  Github_fetch/preview.png
  Github_fetch/script.js
  Github_fetch/style.css
Labels: GSSoC22, Level3

#211 Interactive Animated Login / Signup form
  Interactive Animated LoginSignup Form/README.md
  Interactive Animated LoginSignup Form/index.html
  Interactive Animated LoginSignup Form/script.js
  Interactive Animated LoginSignup Form/style.css
Labels: GSSoC22, Level2

#212 Added the code for Tic Tac Toe in games folder
  Games/Tic-Tac-Toe/.vscode/settings.json
  Games/Tic-Tac-Toe/code.html
  Games/Tic-Tac-Toe/file.js
  Games/Tic-Tac-Toe/game-over).wav
  Games/Tic-Tac-Toe/game_over.wav
  Games/Tic-Tac-Toe/start.wav
  Games/Tic-Tac-Toe/style.css
  Games/Tic-Tac-Toe/tic_tac_toe_wallpaper.jpg
Labels: GSSoC22, Level2

#219 TicTacToe
  Tic-Tac-Toe Game/README.md
  Tic-Tac-Toe Game/index.html
  Tic-Tac-Toe Game/script.js
  Tic-Tac-Toe Game/style.css
  Tic-Tac-Toe Game/tictactoe-dark.png
  Tic-Tac-Toe Game/tictactoe-light.png
Labels: GSSoC22, Level2

#222 Image Filter App
  Image-Filter-App/Image-Filter-App.png
  Image-Filter-App/README.md
  Image-Filter-App/index.html
  Image-Filter-App/script.js
  Image-Filter-App/style.css
Labels: GSSoC22, Level3

#224 Google meet UI
  Google Meet UI/Google Meet_files/google_meet_horizontal_wordmark_2020q4_1x_icon_124_40_2373e79660dabbf194273d27aa7ee1f5.png
  Google Meet UI/Google Meet_files/security_shield_356739b7c38934eec8fb0c8e93de8543.svg
  Google Meet UI/Google Meet_files/unnamed.png
  Google Meet UI/Google Meet_files/user_edu_brady_bunch_light_81fa864771e5c1dd6c75abe020c61345.svg
  Google Meet UI/Google Meet_files/user_edu_get_a_link_light_90698cd7b4ca04d3005c962a3756c42d.svg
  Google Meet UI/Google Meet_files/user_edu_safety_light_e04a2bbb449524ef7e49ea36d5f25b65.svg
  Google Meet UI/Google Meet_files/user_edu_scheduling_light_b352efa017e4f8f1ffda43e847820322.svg
  Google Meet UI/index.html
  Google Meet UI/readme.md
Labels: GSSoC22, Level2

#226 Shopify Website Clone
  Shopify Website Clone/Create your ecommerce store with Shopify_files/css1.css
  Shopify Website Clone/index.html
  Shopify Website Clone/readme.md
Labels: GSSoC22, Level3

#242 Added Codegym Website Clone
  Online Tutorial to Learn Java - CodeGym_files/BenefitsSectionCase1.webp
  Online Tutorial to Learn Java - CodeGym_files/BenefitsSectionCase2.webp
  Online Tutorial to Learn Java - CodeGym_files/BenefitsSectionCase3.webp
  Online Tutorial to Learn Java - CodeGym_files/HeroDecorationCoffeecupLight.webp
  Online Tutorial to Learn Java - CodeGym_files/HeroDecorationGlassLight.webp
  Online Tutorial to Learn Java - CodeGym_files/HeroDecorationNotebookLight.webp
  Online Tutorial to Learn Java - CodeGym_files/HeroDecorationToyLight.webp
  Online Tutorial to Learn Java - CodeGym_files/InfoSectionCodingLight.svg
  Online Tutorial to Learn Java - CodeGym_files/InfoSectionInstantVerificationLight.svg
  Online Tutorial to Learn Java - CodeGym_files/InfoSectionJavaManLight.svg
  Online Tutorial to Learn Java - CodeGym_files/InfoSectionPractice2Light.svg
  Online Tutorial to Learn Java - CodeGym_files/InfoSectionPracticeLight.svg
  Online Tutorial to Learn Java - CodeGym_files/InfoSectionTeachingLight.svg
  Online Tutorial to Learn Java - CodeGym_files/app-store.svg
  Online Tutorial to Learn Java - CodeGym_files/google-play.svg
  Online Tutorial to Learn Java - CodeGym_files/huawei-app-gallery.svg
  Online Tutorial to Learn Java - CodeGym_files/index-ce520308.css
  Online Tutorial to Learn Java - CodeGym_files/logo-cg--light.svg
  Online Tutorial to Learn Java - CodeGym_files/logo-cg-full.svg
  Online Tutorial to Learn Java - CodeGym_files/mastercard.svg
  Online Tutorial to Learn Java - CodeGym_files/sidebar-cg-logo.svg
  Online Tutorial to Learn Java - CodeGym_files/visa.svg
  index.html
Labels: GSSoC22, Level3

#240 Added responsive product card UI
  Product_Display_Cards/Product_Card_06/Readme.md
  Product_Display_Cards/Product_Card_06/assets/Product1.png
  Product_Display_Cards/Product_Card_06/assets/Product2.png
  Product_Display_Cards/Product_Card_06/assets/Product3.png
  Product_Display_Cards/Product_Card_06/code/index.html
  Product_Display_Cards/Product_Card_06/code/script.js
  Product_Display_Cards/Product_Card_06/code/style.css
Labels: GSSoC22, Level3

#238 Google Clone
  google ui/README.md
  google ui/index.html
  google ui/style.css
Labels: GSSoC22, Level2

#235 Card-with-Glasseffect
  Card-with-Glasseffect/Readme.md
  Card-with-Glasseffect/index.html
  Card-with-Glasseffect/style.css
Labels: GSSoC22, Level2

#237 Moving space animation
  Moving space animation/Readme.md
  Moving space animation/astronaut.png
  Moving space animation/background.jpg
  Moving space animation/comet.png
  Moving space animation/index.html
  Moving space animation/moon.png
  Moving space animation/space_ship.png
  Moving space animation/stars.png
  Moving space animation/style.css
Labels: GSSoC22, Level2

#231 Random Password Generator
  Random Password Generator/index.html
  Random Password Generator/index.js
  Random Password Generator/styles.css
Labels: GSSoC22, Level2

#232 meme_generator added.
  Meme_generator/README.md
  Meme_generator/index.html
  Meme_generator/preview.png
  Meme_generator/script.js
  Meme_generator/style.css
Labels: GSSoC22, Level3

#236 Quote of the day
  Quote of the day/Readme.md
  Quote of the day/index.html
  Quote of the day/script.js
  Quote of the day/style.css
Labels: GSSoC22, Level2

#250 Added Udemy Website UI Clone
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/1565838_e54e_16.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/1754098_e0df_3.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/2196488_8fc7_8.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/2776760_f176_10.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/394676_ce3d_5.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/396876_cc92_7.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/405878_e5a0_3.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/449532_2aa9_7.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/482754_7146_6.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/4f8bb0a0-bacb-47b7-9dd5-cfe72681a0ea.png
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/914296_3670_8.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/box-dark.svg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/css1.css
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/eventbrite-dark.svg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/instructor-1x-v3.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/logo-ub.svg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/logo-udemy-inverted.svg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/logo-udemy.svg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/lohp-category-business-v2.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/lohp-category-design-v2.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/lohp-category-development-v2.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/lohp-category-it-and-software-v2.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/lohp-category-marketing-v2.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/lohp-category-music-v2.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/lohp-category-personal-development-v2.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/lohp-category-photography-v2.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/nasdaq-dark.svg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/netapp-dark.svg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/transform-1x-v3.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/ub-1x-v3.jpg
  Online Courses - Learn Anything, On Your Schedule _ Udemy_files/volkswagen-dark.svg
  index.html
Labels: GSSoC22, Level3

#254 Added FAQ project.
  FAQ/README.md
  FAQ/index.html
  FAQ/preview.png
  FAQ/script.js
  FAQ/style.css
Labels: GSSoC22, Level2

#255 Survey form added.
  surveyForm/README.md
  surveyForm/index.html
  surveyForm/preview.png
  surveyForm/style.css
Labels: GSSoC22, Level3

#259 Login Sign Up Form Flip Card
  Login Form Fip/README.md
  Login Form Fip/index.html
  Login Form Fip/script.js
  Login Form Fip/style.css
  Random Password Generator/index.html
  random Password generator/index.html
Labels: GSSoC22, Level2

#256 Know-your-number
  Know-your-number/Readme.md
  index.html
  script.js
  style.css
Labels: GSSoC22, Level2

#262 Added To Do List App
  To-Do List App/Readme.md
  To-Do List App/code/index.html
  To-Do List App/code/script.js
  To-Do List App/code/style.css
Labels: GSSoC22, Level3

#264 ID Card Generator
  ID Card Generator DEZENIX/README.md
  ID Card Generator DEZENIX/index.html
  ID Card Generator DEZENIX/script.js
  ID Card Generator DEZENIX/style.css
Labels: GSSoC22, Level3

#273 Social Badges Animation
  Social badges/README.md
  Social badges/index.html
  Social badges/style.css
Labels: GSSoC22, Level2

#274 Bubble Cards Effect
  Cards On Hover/README.md
  Cards On Hover/index.html
  Cards On Hover/style.css
Labels: GSSoC22, Level2

#275 Moon Eclipse Animation
  Moon Eclipse Animation/README.md
  Moon Eclipse Animation/index.html
  Moon Eclipse Animation/style.css
Labels: GSSoC22, Level2

#276 Nike-shoe design Landing page added.
  Automative-car page/README.md
  Automative-car page/car-bg.jpg
  Automative-car page/index.html
  Automative-car page/preview.png
  Automative-car page/style.css
  Nike-shoe-design/README.md
  Nike-shoe-design/index.html
  Nike-shoe-design/shoe-1.jpg
  Nike-shoe-design/shoePreview.png
  Nike-shoe-design/style.css
Labels: GSSoC22, Level3

#281 Added stackoverflow Website Clone
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(1).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(10).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(11).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(2).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(3).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(4).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(5).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(6).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(7).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(8).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon(9).png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/apple-touch-icon.png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/barkbox-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/bloomberg-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/box-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/css1.css
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/dialpad-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/expensify-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-code.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-for-you.png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-home-search.png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-integrations-left.png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-integrations-right.png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-public.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-question.png
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-se.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/illo-teams.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/instacart-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/intercom-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/microsoft-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/microsoft-teams-logo.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/overstock-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/philips-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/siemens-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/teams-illo-free-sidebar-promo.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/verizon-media-alt.svg
  Stack Overflow - Where Developers Learn, Share, & Build Careers_files/wisetech-global-alt.svg
  index.html
Labels: GSSoC22, Level3

#283 Rock paper Scissor game
  rock paper scissor/README.md
  rock paper scissor/index.html
  rock paper scissor/script.js
  rock paper scissor/style.css
Labels: GSSoC22, Level2

#284 Dezenix Info Cards
  Dezenix Info card/README.md
  Dezenix Info card/index.html
  Dezenix Info card/style.css
Labels: GSSoC22, Level2

#287 Added NSS Website UI
  NSS Website Clone/Home _ National Service Scheme_files/1649323913104_ganga.jpg1_.jpg
  NSS Website Clone/Home _ National Service Scheme_files/400X300.jpg
  NSS Website Clone/Home _ National Service Scheme_files/FB_IMG_1643385282118_0.jpg
  NSS Website Clone/Home _ National Service Scheme_files/IMG-20220126-WA0011_0.jpg
  NSS Website Clone/Home _ National Service Scheme_files/IMG-20220128-WA0014_1.jpg
  NSS Website Clone/Home _ National Service Scheme_files/IndianRedCrossSociety.png
  NSS Website Clone/Home _ National Service Scheme_files/Manual_cover - Copy.jpg
  NSS Website Clone/Home _ National Service Scheme_files/athakur.jpg
  NSS Website Clone/Home _ National Service Scheme_files/bharat scouts and guides.png
  NSS Website Clone/Home _ National Service Scheme_files/cmf-logo.png
  NSS Website Clone/Home _ National Service Scheme_files/data-gov.png
  NSS Website Clone/Home _ National Service Scheme_files/download_2.jpg
  NSS Website Clone/Home _ National Service Scheme_files/facebook.png
  NSS Website Clone/Home _ National Service Scheme_files/imageedit_1_2626406453.jpg
  NSS Website Clone/Home _ National Service Scheme_files/imageedit_1_7308790992.jpg
  NSS Website Clone/Home _ National Service Scheme_files/imageedit_3_5213179193.jpg
  NSS Website Clone/Home _ National Service Scheme_files/incredible-india.png
  NSS Website Clone/Home _ National Service Scheme_files/india-gov.png
  NSS Website Clone/Home _ National Service Scheme_files/logo-black.png
  NSS Website Clone/Home _ National Service Scheme_files/logo.png
  NSS Website Clone/Home _ National Service Scheme_files/moca_crasoul3_0.png
  NSS Website Clone/Home _ National Service Scheme_files/moca_crasoul5.png
  NSS Website Clone/Home _ National Service Scheme_files/moefnew.png
  NSS Website Clone/Home _ National Service Scheme_files/mygov.png
  NSS Website Clone/Home _ National Service Scheme_files/ncc_logo.png
  NSS Website Clone/Home _ National Service Scheme_files/nyf2022 1180.jpg
  NSS Website Clone/Home _ National Service Scheme_files/pariksha pr charcha.jpg
  NSS Website Clone/Home _ National Service Scheme_files/partner04.jpg
  NSS Website Clone/Home _ National Service Scheme_files/partner08.jpg
  NSS Website Clone/Home _ National Service Scheme_files/styles.css
  NSS Website Clone/Home _ National Service Scheme_files/twitter.png
  NSS Website Clone/Home _ National Service Scheme_files/video.jpg
  NSS Website Clone/index.html
  NSS Website Clone/readme.md
Labels: GSSoC22, Level3

#289 Added Just Dial Website UI
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/Doctors.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/Flights.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/app_familybg.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/automobile.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/cfonts.css
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/daily.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/easymytrip_logo.png
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/flower.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/jdlogosvg.svg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/jdmart-banner.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/jobs-compressor.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/loans.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/logistic-banner-web.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/ondemand.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/personal_care.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/real_estate.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/repairs.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/restaurant.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/shopfront.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/tickmark.png
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/travel.jpg
  Just Dial Website Clone/Justdial - Local Search, Social, News, Videos, Shopping_files/wedding.jpg
  Just Dial Website Clone/index.html
  Just Dial Website Clone/readme.md
Labels: GSSoC22, Level3

#292 Weight-converter
  Weight-converter/Readme.md
  Weight-converter/index.html
  Weight-converter/script.js
  Weight-converter/style.css
Labels: GSSoC22, Level2

#293 Qr_code_generator
  Qr_code_generator/Readme.md
  Qr_code_generator/index.html
  Qr_code_generator/script.js
  Qr_code_generator/style.css
Labels: GSSoC22, Level2

#294 Get-Your-GitHub-profile
  Get-Your-GitHub profile/Readme.md
  Get-Your-GitHub profile/index.html
  Get-Your-GitHub profile/script.js
  Get-Your-GitHub profile/style.css
Labels: GSSoC22, Level2

#295 Fortune teller Crystal Ball
  Fortune Teller Crystal Ball/Crystal-Ball-PNG-Photos.png
  Fortune Teller Crystal Ball/README.md
  Fortune Teller Crystal Ball/index.html
  Fortune Teller Crystal Ball/script.js
  Fortune Teller Crystal Ball/style.css
Labels: GSSoC22, Level3

#297 Added You Website Clone
  You Website Clone/YOU.html
  You Website Clone/YOU_files/android.png
  You Website Clone/YOU_files/app-store.png
  You Website Clone/YOU_files/apple.png
  You Website Clone/YOU_files/broadband-plans_ver-2.jpg
  You Website Clone/YOU_files/captcha.jpg
  You Website Clone/YOU_files/fup.png
  You Website Clone/YOU_files/google-play.png
  You Website Clone/YOU_files/logo-2017.png
  You Website Clone/YOU_files/love.png
  You Website Clone/YOU_files/main.min.css
  You Website Clone/YOU_files/mobile-app-main.jpg
  You Website Clone/YOU_files/outdatedbrowser.min.css
  You Website Clone/YOU_files/rollover-banner-v3.jpg
  You Website Clone/readme.md
Labels: GSSoC22, Level3

#332 Lee Fashion Website Clone
  Lee/README.md
  Lee/index.html
  Lee/style.css
Labels: GSSoC22, Level3

#302 Fylo Landing page added.
  FyloLandingPage/FyloPreview.png
  FyloLandingPage/README.md
  FyloLandingPage/images/avatar-testimonial.jpg
  FyloLandingPage/images/bg-curve-desktop.svg
  FyloLandingPage/images/bg-curve-mobile.svg
  FyloLandingPage/images/favicon-32x32.png
  FyloLandingPage/images/icon-arrow.svg
  FyloLandingPage/images/icon-email.svg
  FyloLandingPage/images/icon-phone.svg
  FyloLandingPage/images/icon-quotes.svg
  FyloLandingPage/images/illustration-1.svg
  FyloLandingPage/images/illustration-2.svg
  FyloLandingPage/images/logo.svg
  FyloLandingPage/index.html
  FyloLandingPage/style.css
  Random Password Generator/index.js
  Random Password Generator/styles.css
  random Password generator/README.md
  random Password generator/script.js
  random Password generator/style.css
Labels: GSSoC22, Level3

#305 Animated Loading Bar
  bouncing animation/README.md
  bouncing animation/index.html
  bouncing animation/style.css
Labels: GSSoC22, Level2

#306 Liquid Text Animation
  Liquid Text/README.md
  Liquid Text/index.html
  Liquid Text/style.css
Labels: GSSoC22, Level2

#312 Added Quickr website UI
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Accessories.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Apartments_for_Rent.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Apartments_for_Sale.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/BPO_jobs.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Clothing.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Commercial_Property_for_Rent.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Commercial_Property_for_Sale.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Computer-peripherals.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Kitchen-appliances.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Mobiles.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Musical-instruments.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Office-furniture.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/PG_Flatmates.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Plot_for_Sale.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Residential_Projects_for_Sale.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Residential_Properties_by_Owner.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Sport-Fitness-equipment.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/TV-DVD-Multimedia.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/Villa_for_Sale.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/ak_1430424351-1637219965.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/career-counselling.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/cars_bikes.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/certification-training.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/colleges.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/default_1.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/distance-learning.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/driver_jobs.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/electronics_appliances.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/exam-coaching.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/headercssv2-ae240a4f997ea229f0c0.css
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/home-cleaning3.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/home_lifestyle.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/hospitality_jobs.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/interior-designing1.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/iphone.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/jobs.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/laptops-computers.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/mobiles_tablets.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/packers-movers3.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/pest-control3.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/play-school.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/quikr_logo.png
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/school-tuitions.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/study-abroad.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/tablet.jpg
  Quickr Website UI/Free Classified Ads in Vizag, Post Ads Online _ Quikr Vizag_files/teacher_jobs.png
  Quickr Website UI/index.html
  Quickr Website UI/readme.md
Labels: GSSoC22, Level3

#314 Programmer's Motivational Quotes Generator
  Programmer's Motivational Quotes Generator/README.md
  Programmer's Motivational Quotes Generator/index.html
  Programmer's Motivational Quotes Generator/script.js
  Programmer's Motivational Quotes Generator/style.css
Labels: GSSoC22, Level2

#318 Product Landing page added.
  Product_landing/README.md
  Product_landing/index.html
  Product_landing/productLanding.png
  Product_landing/style.css
Labels: GSSoC22, Level3

#319 Wrangler Clone
  Wrangler/README.md
  Wrangler/index.html
  Wrangler/style.css
Labels: GSSoC22, Level3

#325 Type Writer Animation
  Type Writr Animation/README.md
  Type Writr Animation/index.html
  Type Writr Animation/style.css
Labels: GSSoC22, Level2

#326 Cross FAde Animation
  Cross fade animation/README.md
  Cross fade animation/index.html
  Cross fade animation/style.css
Labels: GSSoC22, Level2

#327 Charging animation
  Charging Animation/README.md
  Charging Animation/index.html
  Charging Animation/style.css
Labels: GSSoC22, Level2

#328 Hidden Content reveal card
  hidden content reveal card/README.md
  hidden content reveal card/index.html
  hidden content reveal card/style.css
Labels: GSSoC22, Level2

#330 Check the special number
  Check the special number/Readme.md
  Check the special number/index.html
  Check the special number/script.js
  Check the special number/style.css
Labels: GSSoC22, Level3

#337 Accusoft Website UI
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/EzeScan-Logo.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/Icon_Cloud_Hosted.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/PDF-API-SDK-Cloud.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/accusoft-logo-reverse@2x.png
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/accusoft-master-logo.svg
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/all.css
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/check_icon.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/icon_On_Prem.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/logo_brother_white_500.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/logo_hyland_white_500.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/logo_opentext_white_500.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/logo_uspto_white_500.png.webp
  Accusoft Website UI/Accusoft _ PDF API _ View, Annotate, Convert, & Compress._files/tag.aspx
  Accusoft Website UI/index.html
  Accusoft Website UI/readme.md
Labels: GSSoC22, Level3

#339 Added Clone of Excitel Website
  Exictel Website UI/Excitel.html
  Exictel Website UI/Excitel_files/AuthenticationService.Authenticate
  Exictel Website UI/Excitel_files/Banner.webp
  Exictel Website UI/Excitel_files/__styles.css
  Exictel Website UI/Excitel_files/form-open-btn.webp
  Exictel Website UI/Excitel_files/ico1.webp
  Exictel Website UI/Excitel_files/ico2.webp
  Exictel Website UI/Excitel_files/ico3.webp
  Exictel Website UI/Excitel_files/logo.webp
  Exictel Website UI/Excitel_files/style(1).css
  Exictel Website UI/Excitel_files/style.css
  Exictel Website UI/Excitel_files/style.min.css
  Exictel Website UI/Excitel_files/styles.css
  Exictel Website UI/Excitel_files/target.webp
  Exictel Website UI/Excitel_files/undo_poly.png
  Exictel Website UI/readme.md
Labels: GSSoC22, Level3

#341 Added Animated new year countdown.
  Animated_new_year/README.md
  Animated_new_year/index.html
  Animated_new_year/newYear.png
  Animated_new_year/script.js
  Animated_new_year/spinner.gif
  Animated_new_year/style.css
Labels: GSSoC22, Level2

#349 BMI Calculator
  BMI Calculator/Readme.md
  BMI Calculator/index.html
  BMI Calculator/script.js
  BMI Calculator/style.css
Labels: GSSoC22, Level3

#352 Content Card Reveal
  Card-content-reveal/Readme.md
  Card-content-reveal/bg.jpg
  Card-content-reveal/index.html
  Card-content-reveal/style.css
Labels: GSSoC22, Level2

#363 Text to speech
  Text to speech/README.md
  Text to speech/index.html
  Text to speech/script.js
  Text to speech/style.css
Labels: GSSoC22, Level3

#368 Linktree clone
  Linktree/README.md
  Linktree/asset/256px-Icon-notepad.svg.png
  Linktree/asset/Screenshot 2022-05-29 110030.png
  Linktree/asset/discord-new-20218785-removebg-preview.png
  Linktree/asset/github.png
  Linktree/asset/instagram (1).png
  Linktree/asset/linkedin.png
  Linktree/asset/telegram.png
  Linktree/asset/whatsapp (1).png
  Linktree/asset/ylang.mp3
  Linktree/asset/youtube-featured-removebg-preview.png
  Linktree/css/style.css
  Linktree/index.html
Labels: GSSoC22, Level3

#371 Added responsive Ip tracker
  Ip Tracker/Readme.md
  Ip Tracker/code/index.html
  Ip Tracker/code/script.js
  Ip Tracker/code/style.css
Labels: GSSoC22, Level2

#369 Drum
  Drum/README.md
  Drum/css/style.css
  Drum/images/256px-Icon-notepad.svg.png
  Drum/images/Web capture_29-5-2022_122746_127.0.0.1.jpeg
  Drum/images/crash.png
  Drum/images/kick.png
  Drum/images/snare.png
  Drum/images/tom1.png
  Drum/images/tom2.png
  Drum/images/tom3.png
  Drum/images/tom4.png
  Drum/index.html
  Drum/js/script.js
  Drum/sounds/crash.mp3
  Drum/sounds/kick-bass.mp3
  Drum/sounds/snare.mp3
  Drum/sounds/tom-1.mp3
  Drum/sounds/tom-2.mp3
  Drum/sounds/tom-3.mp3
  Drum/sounds/tom-4.mp3
Labels: GSSoC22, Level2

#370 Added Animated Earth project.
  Animated Earth/README.md
  Animated Earth/images/earth-day.jpg
  Animated Earth/images/earth-night.jpg
  Animated Earth/index.html
  Animated Earth/style.css
Labels: GSSoC22, Level2

#359 Siren Spinner
  siren Spinner/README.md
  siren Spinner/index.html
  siren Spinner/style.css
Labels: GSSoC22, Level2

#361 Official Lee Cooper Clone
  leeCooper/README.md
  leeCooper/index.html
  leeCooper/style.css
Labels: GSSoC22, Level3

#362 Mine Craft Spider Loader
  Minecraft Spider Loader/README.md
  Minecraft Spider Loader/index.html
  Minecraft Spider Loader/style.css
Labels: GSSoC22, Level2

#365 Floating Cards
  Floating Cards Animation/README.md
  Floating Cards Animation/index.html
  Floating Cards Animation/style.css
Labels: GSSoC22, Level2

#382 Palindrome checker
  Palindrome checker/Readme.md
  Palindrome checker/index.html
  Palindrome checker/script.js
  Palindrome checker/style.css
Labels: GSSoC22, Level2

#383 Recipe-app
  Recipe-app/Readme.md
  Recipe-app/index.html
  Recipe-app/script.js
  Recipe-app/style.css
Labels: GSSoC22, Level3

#385 Added InternFreak Clone
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/Acko.png
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/Couchbase.png
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/Lexmark.png
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/Optum.png
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/QUAD.png
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/Wiley Edge.png
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/logo.webp
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/slider1.png
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/slider2.svg
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/slider3.svg
  InternFreak Clone/Part-Time Jobs Vacancy In Bangalore & Pune- Internfreak.co_files/style.css
  InternFreak Clone/index.html
  InternFreak Clone/readme.md
Labels: GSSoC22, Level3

#401 Fingerprint animation loade
  FingerPrint Loader/README.md
  FingerPrint Loader/index.html
  FingerPrint Loader/style.css
Labels: GSSoC22, Level2

#402 Checkbox Animation
  checkbox animation/README.md
  checkbox animation/index.html
  checkbox animation/style.css
Labels: GSSoC22, Level2

#404 3D Button Animation
  3D Button/README.md
  3D Button/index.html
  3D Button/style.css
Labels: GSSoC22, Level2

#405 CoC Clone
  Clash of Clan/README.md
  Clash of Clan/Screenshot (371).png
  Clash of Clan/index.html
  Clash of Clan/style.css
Labels: GSSoC22, Level3

#406 Fingerprint scanner animation
  Fingerprint scanner animation/README.md
  Fingerprint scanner animation/fingerPrint_01.png
  Fingerprint scanner animation/fingerPrint_02.png
  Fingerprint scanner animation/index.html
  Fingerprint scanner animation/style.css
Labels: GSSoC22, Level2

#407 flower
  flower/README.md
  flower/index.html
  flower/style.css
Labels: GSSoC22, Level2

#408 Emoji Smasher Game (Smash Em' All 😈)
  Smash em All/5862951a3796e30ac4468737.png
  Smash em All/586295b33796e30ac4468738.png
  Smash em All/58e8fe3beb97430e819064c4.png
  Smash em All/58e8ff10eb97430e819064cc.png
  Smash em All/README.md
  Smash em All/hammer.png
  Smash em All/index.html
  Smash em All/script.js
  Smash em All/style.css
Labels: GSSoC22, Level3

#409 Random jokes Generator
  Random Jokes Generator/README.md
  Random Jokes Generator/css/style.css
  Random Jokes Generator/img/256px-Icon-notepad.svg.png
  Random Jokes Generator/img/Screenshot 2022-05-30 100612.png
  Random Jokes Generator/index.html
  Random Jokes Generator/js/script.js
Labels: GSSoC22, Level2

#410 Random hex generator
  Random hex generator/README.md
  Random hex generator/index.html
  Random hex generator/script.js
  Random hex generator/style.css
Labels: GSSoC22, Level2

#423 Added Fashion webpage.
  Fashion_webpage/192.168.196.73_5500_index.html.png
  Fashion_webpage/Images/img-1.jpg
  Fashion_webpage/Images/img-2.jpg
  Fashion_webpage/README.md
  Fashion_webpage/index.html
  Fashion_webpage/style.css
Labels: GSSoC22, Level3

#421 Adde Tourist landing page.
  Tourist landing page/README.md
  Tourist landing page/index.html
  Tourist landing page/preview.png
  Tourist landing page/style.css
Labels: GSSoC22, Level2

#418 svg animated webpage
  svg webpage/README.md
  svg webpage/index.html
  svg webpage/samsung-mobile-png-14.png
  svg webpage/style.css
  svg webpage/tree-736885__480.jpg
Labels: GSSoC22, Level2

#417 battery shower
  Battery shower/README.md
  Battery shower/css/style.css
  Battery shower/img/256px-Icon-notepad.svg.png
  Battery shower/img/Screenshot 2022-05-30 133137(2).png
  Battery shower/img/Screenshot 2022-05-30 133137.png
  Battery shower/index.html
  Battery shower/js/script.js
Labels: GSSoC22, Level2

#416 Decimal To Binary Converter
  Decimal To Binary Converter/README.md
  Decimal To Binary Converter/css/style.css
  Decimal To Binary Converter/img/256px-Icon-notepad.svg.png
  Decimal To Binary Converter/img/Screenshot 2022-05-30 130351.png
  Decimal To Binary Converter/index.html
  Decimal To Binary Converter/js/script.js
Labels: GSSoC22, Level2

#415 Added sticky notes app
  Sticky Notes/Readme.md
  Sticky Notes/code/index.html
  Sticky Notes/code/script.js
  Sticky Notes/code/style.css
Labels: GSSoC22, Level2

#425 Added Act Website Clone
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/Aha-new.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/Entertainment_card_zee5_482x805_1.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/Entertainmentcard_roland_garros_174x291.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/Shield.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/Zee5_logo_0.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/a50c0a46b29d16f4138a8509428a83f6.css
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/ba8323ddcb2d1992ee32e05e4c3ea732.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/choose-good-broadband-provider-for-home-business-thumb.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/cultfit.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/curefit_entertainment card.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/entertainment_card_aha_web.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/epicon-entertainment-card-web.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/epicon-logo.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/gaming.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/gaming_entertainment card.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/get-your-office-connected-with-fiber-internet-connection-thumb.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/how-do-i-decide--right-broadband-speed-thumb.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/hungama-entertainment-card-web.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/hungama.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/logo.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/managed-4-wi-fi-networks-why-do-you-need-it-thumb.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/shield_entertainment card.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/sony-logo.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/tips-for-faster-online-gaming-experience-with-wi-fi-connection-thumb.jpg
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/user-all.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/user_icon_testimonials.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/user_icon_testimonials_10.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/user_icon_testimonials_11.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/user_icon_testimonials_12.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/user_icon_testimonials_13.png
  ACT Website Clone/Broadband Connection _ Internet Service Provider _ ACT Fibernet_files/user_icon_testimonials_8.png
  ACT Website Clone/index.html
  ACT Website Clone/readme.md
Labels: GSSoC22, Level3

#427 Added Simple Yahoo Search UI
  Yahoo Search/index.html
  Yahoo Search/readme.md
Labels: GSSoC22, Level3

#432 Make show hide password
  ShowHidePassword/index.html
  ShowHidePassword/script.js
  ShowHidePassword/style.css
Labels: GSSoC22, Level2

#430 Diesel Clone
  Deisel/README.md
  Deisel/index.html
  Deisel/style.css
Labels: GSSoC22, Level3

#445 text Switcher
  text Switcher/README.md
  text Switcher/index.html
  text Switcher/style.css
Labels: GSSoC22, Level3

#446 Neon Lights
  neon lights/README.md
  neon lights/index.html
  neon lights/style.css
Labels: GSSoC22, Level3

#447 see saw game
  see saw game/README.md
  see saw game/index.html
  see saw game/style.css
Labels: GSSoC22, Level3

#448 Responsive sidebar
  Side-bar/README.md
  Side-bar/index.html
  Side-bar/script.js
  Side-bar/style.css
Labels: GSSoC22, Level3

#453 add currency convertor
  currecyConvertor/app.js
  currecyConvertor/index.html
  currecyConvertor/style.css
Labels: GSSoC22, Level3

#454 Simple Library Management Added
  Simple Libray Management/images/SimpleLibraryManagement(mobile).png
  Simple Libray Management/images/SimpleLibraryManagement.png
  Simple Libray Management/index.html
  Simple Libray Management/readme.md
  Simple Libray Management/script.js
Labels: GSSoC22, Level3
